services:
  easy-wol:
    build: .
    container_name: easy-wol-dev
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: "8080"
      ADMIN_PASSWORD: "change-this-password"
      DB_PATH: "/app/data/easy-wol.sqlite"
      SSH_KEY_DIR: "/app/ssh"
    volumes:
      - ./data:/app/data
      - ./ssh-keys:/app/ssh:ro
